// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_numerov
List rcpp_numerov();
RcppExport SEXP numerov_rcpp_numerov() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_numerov());
    return rcpp_result_gen;
END_RCPP
}
// getEnergiesAndIndices
List getEnergiesAndIndices();
RcppExport SEXP numerov_getEnergiesAndIndices() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getEnergiesAndIndices());
    return rcpp_result_gen;
END_RCPP
}
// setPotential
void setPotential(NumericVector px, NumericVector py);
RcppExport SEXP numerov_setPotential(SEXP pxSEXP, SEXP pySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type px(pxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py(pySEXP);
    setPotential(px, py);
    return R_NilValue;
END_RCPP
}
// getPotential
List getPotential();
RcppExport SEXP numerov_getPotential() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getPotential());
    return rcpp_result_gen;
END_RCPP
}
// computeSpectrum
void computeSpectrum(int nEigen, double dE, double tol);
RcppExport SEXP numerov_computeSpectrum(SEXP nEigenSEXP, SEXP dESEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nEigen(nEigenSEXP);
    Rcpp::traits::input_parameter< double >::type dE(dESEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    computeSpectrum(nEigen, dE, tol);
    return R_NilValue;
END_RCPP
}
// getEnergies
NumericVector getEnergies();
RcppExport SEXP numerov_getEnergies() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getEnergies());
    return rcpp_result_gen;
END_RCPP
}
// getWavefunctions
List getWavefunctions();
RcppExport SEXP numerov_getWavefunctions() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getWavefunctions());
    return rcpp_result_gen;
END_RCPP
}
